begin;

create table if not exists public.app_user_access_audit (
    id bigint generated by default as identity primary key,
    user_name text not null,
    old_role text not null,
    new_role text not null,
    old_is_active boolean not null,
    new_is_active boolean not null,
    changed_by text not null,
    changed_at timestamptz not null default now()
);

create index if not exists app_user_access_audit_user_time_idx
    on public.app_user_access_audit (user_name, changed_at desc);

create or replace function public.update_app_user_access(
    p_username text,
    p_role text,
    p_is_active boolean,
    p_changed_by text
)
returns table (
    user_name text,
    role text,
    is_active boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
    current_role text;
    current_active boolean;
    actor_is_admin boolean;
    normalized_username text := trim(p_username);
    normalized_actor text := trim(p_changed_by);
begin
    if p_role not in (
        'visitor', 'supervisor', 'producer', 'warehouse',
        'after_sales', 'finance', 'admin'
    ) then
        raise exception 'Unsupported role';
    end if;

    select exists (
        select 1
        from public.users actor
        where actor.user_name = normalized_actor
          and coalesce(actor.role, 'visitor') = 'admin'
          and coalesce(actor.is_active, true) = true
    ) into actor_is_admin;

    if not actor_is_admin then
        raise exception 'Only an active admin can change access';
    end if;

    select coalesce(u.role, 'visitor'), coalesce(u.is_active, true)
    into current_role, current_active
    from public.users u
    where u.user_name = normalized_username
    for update;

    if not found then
        raise exception 'User not found';
    end if;

    if normalized_username = normalized_actor
       and (p_role <> 'admin' or not p_is_active) then
        raise exception 'Admin cannot remove own access';
    end if;

    if current_role = p_role and current_active = p_is_active then
        return query select normalized_username, current_role, current_active;
        return;
    end if;

    update public.users u
    set role = p_role, is_active = p_is_active
    where u.user_name = normalized_username;

    insert into public.app_user_access_audit (
        user_name, old_role, new_role, old_is_active, new_is_active, changed_by
    ) values (
        normalized_username, current_role, p_role,
        current_active, p_is_active, normalized_actor
    );

    return query select normalized_username, p_role, p_is_active;
end;
$$;

revoke all on function public.update_app_user_access(
    text, text, boolean, text
) from public, anon, authenticated;
grant execute on function public.update_app_user_access(
    text, text, boolean, text
) to service_role;

grant select on public.app_user_access_audit to service_role;

commit;

notify pgrst, 'reload schema';
