begin;

create table if not exists public.app_permissions (
    permission_key text primary key,
    permission_name text not null,
    permission_group text not null,
    description text not null default '',
    sort_order integer not null default 0
);

create table if not exists public.app_roles (
    role_key text primary key,
    role_name text not null,
    description text not null default '',
    is_system boolean not null default false,
    created_by text not null default 'migration',
    created_at timestamptz not null default now(),
    updated_by text not null default 'migration',
    updated_at timestamptz not null default now(),
    constraint app_roles_key_format check (
        role_key ~ '^[a-z][a-z0-9_]{2,31}$'
    )
);

create table if not exists public.app_role_permissions (
    role_key text not null references public.app_roles(role_key) on delete cascade,
    permission_key text not null
        references public.app_permissions(permission_key) on delete cascade,
    primary key (role_key, permission_key)
);

create table if not exists public.app_user_access_audit (
    id bigint generated by default as identity primary key,
    user_name text not null,
    old_role text not null,
    new_role text not null,
    old_is_active boolean not null,
    new_is_active boolean not null,
    changed_by text not null,
    changed_at timestamptz not null default now()
);

create table if not exists public.app_role_change_audit (
    id bigint generated by default as identity primary key,
    role_key text not null,
    action text not null check (action in ('create', 'update')),
    old_snapshot jsonb,
    new_snapshot jsonb not null,
    changed_by text not null,
    changed_at timestamptz not null default now()
);

create index if not exists app_user_access_audit_user_time_idx
    on public.app_user_access_audit (user_name, changed_at desc);
create index if not exists app_role_change_audit_role_time_idx
    on public.app_role_change_audit (role_key, changed_at desc);

commit;
