begin;

create table if not exists public.app_employee_account_audit (
    id bigint generated by default as identity primary key,
    employee_id text not null references public.users(employee_id),
    employee_name text not null,
    old_username text,
    new_username text not null,
    password_reset boolean not null default false,
    old_role text not null,
    new_role text not null,
    old_job_title text not null,
    new_job_title text not null,
    old_departments text[] not null,
    new_departments text[] not null,
    changed_by text not null,
    changed_at timestamptz not null default now()
);

create index if not exists app_employee_account_audit_employee_idx
on public.app_employee_account_audit (employee_id, changed_at desc);

create or replace function public.promote_employee_account(
    p_employee_id text,
    p_username text,
    p_password text,
    p_role text,
    p_job_title text,
    p_departments text[],
    p_changed_by text
)
returns table (
    employee_id text,
    employee_name text,
    user_name text,
    role text,
    job_title text,
    departments text[]
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    normalized_employee_id text := trim(p_employee_id);
    normalized_username text := trim(p_username);
    normalized_role text := trim(p_role);
    normalized_job_title text := trim(p_job_title);
    normalized_actor text := trim(p_changed_by);
    normalized_departments text[];
    target_name text;
    previous_username text;
    previous_role text;
    previous_active boolean;
    previous_job_title text;
    previous_departments text[];
begin
    if not public.app_actor_can_manage_access(normalized_actor) then
        raise exception 'Only an access administrator can promote an employee';
    end if;
    if normalized_employee_id = '' or normalized_username = ''
       or coalesce(p_password, '') = '' or normalized_job_title = '' then
        raise exception 'Employee, username, password and job title are required';
    end if;
    if not exists (
        select 1 from public.app_roles r where r.role_key = normalized_role
    ) then
        raise exception 'Unsupported role';
    end if;
    if exists (
        select 1 from public.users u
        where lower(trim(u.user_name)) = lower(normalized_username)
          and u.employee_id <> normalized_employee_id
    ) then
        raise exception 'Username already exists';
    end if;
    select coalesce(array_agg(
        distinct upper(trim(value)) order by upper(trim(value))
    ), '{}')
    into normalized_departments
    from unnest(coalesce(p_departments, '{}')) value
    where nullif(trim(value), '') is not null;
    if cardinality(normalized_departments) = 0 then
        raise exception 'At least one production department is required';
    end if;
    if exists (
        select 1 from unnest(normalized_departments) code
        where not exists (
            select 1 from public.app_production_departments d
            where d.department_code = code and d.is_active
        )
    ) then
        raise exception 'Unsupported production department';
    end if;

    select u.name, u.user_name, coalesce(u.role, 'visitor'),
           coalesce(u.is_active, true),
           coalesce(nullif(trim(u.job_title), ''), nullif(trim(u.department), ''), '员工')
    into target_name, previous_username, previous_role,
         previous_active, previous_job_title
    from public.users u
    where u.employee_id = normalized_employee_id
    for update;
    if not found then raise exception 'Employee not found'; end if;
    select coalesce(array_agg(d.department_code order by d.department_code), '{}')
    into previous_departments
    from public.app_user_departments d
    where d.employee_id = normalized_employee_id;

    update public.users u
    set user_name = normalized_username,
        password = crypt(p_password, gen_salt('bf', 12)),
        role = normalized_role,
        is_active = true,
        job_title = normalized_job_title,
        department = normalized_job_title
    where u.employee_id = normalized_employee_id;
    delete from public.app_user_departments d
    where d.employee_id = normalized_employee_id;
    insert into public.app_user_departments (
        employee_id, department_code, assigned_by
    ) select normalized_employee_id, code, normalized_actor
      from unnest(normalized_departments) code;

    if previous_role <> normalized_role
       or not previous_active
       or previous_departments <> normalized_departments then
        insert into public.app_user_access_audit (
            user_name, old_role, new_role, old_is_active, new_is_active,
            old_departments, new_departments, changed_by
        ) values (
            normalized_username, previous_role, normalized_role,
            previous_active, true,
            previous_departments, normalized_departments, normalized_actor
        );
    end if;
    if previous_job_title <> normalized_job_title
       or previous_departments <> normalized_departments then
        insert into public.app_employee_profile_audit (
            employee_id, employee_name, old_job_title, new_job_title,
            old_departments, new_departments, changed_by
        ) values (
            normalized_employee_id, target_name,
            previous_job_title, normalized_job_title,
            previous_departments, normalized_departments, normalized_actor
        );
    end if;
    insert into public.app_employee_account_audit (
        employee_id, employee_name, old_username, new_username,
        password_reset, old_role, new_role, old_job_title, new_job_title,
        old_departments, new_departments, changed_by
    ) values (
        normalized_employee_id, target_name, previous_username,
        normalized_username, true, previous_role, normalized_role,
        previous_job_title, normalized_job_title,
        previous_departments, normalized_departments, normalized_actor
    );

    return query select normalized_employee_id, target_name,
        normalized_username, normalized_role, normalized_job_title,
        normalized_departments;
end;
$$;

grant select on public.app_employee_account_audit to service_role;
grant execute on function public.promote_employee_account(
    text, text, text, text, text, text[], text
) to service_role;

commit;

notify pgrst, 'reload schema';
