DEFAULT_CATEGORY = "黑白短袖"
DEFAULT_DEPARTMENT = "DTF"
CATEGORY = DEFAULT_CATEGORY
INVENTORY_CATEGORIES = ["彩色短袖", "黑白短袖", "卫衣"]
SIZE_COLUMNS = ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"]
BLACK_WHITE_MATERIAL_ORDER = {"180g": 0, "160g": 1, "CVC": 2}
BLACK_WHITE_COLOR_ORDER = {"黑": 0, "白": 1}
