begin;

create table if not exists public.after_sales_hotstamp_film_sync_batches (
    id uuid primary key default gen_random_uuid(),
    source_file_id text not null,
    source_file_name text not null,
    source_url text not null default '',
    source_modified_at timestamptz,
    source_hash text not null,
    start_date date not null,
    end_date date not null,
    row_count integer not null default 0 check (row_count >= 0),
    total_film_quantity bigint not null default 0
        check (total_film_quantity >= 0),
    invalid_row_count integer not null default 0
        check (invalid_row_count >= 0),
    operator text not null,
    status text not null default 'completed'
        check (status in ('pending', 'completed', 'failed')),
    created_at timestamptz not null default now(),
    unique (source_file_id, source_hash),
    check (end_date >= start_date)
);

create table if not exists public.after_sales_hotstamp_film_entries (
    id bigint generated by default as identity primary key,
    batch_id uuid not null references
        public.after_sales_hotstamp_film_sync_batches(id) on delete restrict,
    source_file_id text not null,
    source_file_name text not null,
    source_sheet_name text not null,
    source_row_number integer not null check (source_row_number >= 2),
    business_date date not null,
    source_platform text not null,
    platform text not null,
    cutting_person text not null default '',
    matching_person text not null default '',
    film_quantity integer not null check (film_quantity >= 0),
    is_hoodie boolean not null default false,
    multi_press_count integer,
    is_white_board boolean not null default false,
    hotstamp_person text not null default '',
    qa_person text not null default '',
    imported_at timestamptz not null default now(),
    unique (batch_id, source_sheet_name, source_row_number)
);

create index if not exists after_sales_hotstamp_batch_source_time_idx
    on public.after_sales_hotstamp_film_sync_batches (
        source_file_id, created_at desc
    );
create index if not exists after_sales_hotstamp_entry_date_person_idx
    on public.after_sales_hotstamp_film_entries (
        business_date, hotstamp_person, platform
    );
create index if not exists after_sales_hotstamp_entry_batch_idx
    on public.after_sales_hotstamp_film_entries (batch_id);

create or replace view public.after_sales_hotstamp_film_active_entries as
with latest_batches as (
    select distinct on (source_file_id)
        id, source_file_id
    from public.after_sales_hotstamp_film_sync_batches
    where status = 'completed'
    order by source_file_id, created_at desc, id desc
)
select entry.*
from public.after_sales_hotstamp_film_entries entry
join latest_batches batch on batch.id = entry.batch_id;

create or replace function public.normalize_hotstamp_audit_platform(
    source_value text
)
returns text
language sql immutable
as $$
    select case lower(trim(coalesce(source_value, '')))
        when '' then '未标记平台'
        when 'haloo' then 'Haloo'
        when '7创' then '七创'
        when '七创' then '七创'
        when 'sds-1' then 'SDS1'
        when 'sds1' then 'SDS1'
        when 'sds-2' then 'SDS2'
        when 'sds2' then 'SDS2'
        when 'pt莆田' then '莆田'
        when '莆田' then '莆田'
        else trim(source_value)
    end;
$$;

create or replace function public.import_after_sales_hotstamp_film_batch(
    p_source_file_id text,
    p_source_file_name text,
    p_source_url text,
    p_source_modified_at timestamptz,
    p_source_hash text,
    p_start_date date,
    p_end_date date,
    p_rows jsonb,
    p_invalid_row_count integer default 0,
    p_operator text default 'system'
)
returns table (
    batch_id uuid,
    saved_rows integer,
    saved_quantity bigint,
    duplicate boolean
)
language plpgsql security definer set search_path = public
as $$
declare
    v_batch_id uuid;
    v_saved_rows integer := 0;
    v_saved_quantity bigint := 0;
begin
    if trim(coalesce(p_source_file_id, '')) = ''
       or trim(coalesce(p_source_file_name, '')) = '' then
        raise exception '来源文件不能为空';
    end if;
    if p_start_date is null or p_end_date is null
       or p_end_date < p_start_date
       or p_end_date - p_start_date > 7 then
        raise exception '来源周表日期范围无效';
    end if;
    if p_rows is null or jsonb_typeof(p_rows) <> 'array'
       or jsonb_array_length(p_rows) > 5000 then
        raise exception '来源明细必须是最多 5000 行的数组';
    end if;

    select id, row_count, total_film_quantity
    into v_batch_id, v_saved_rows, v_saved_quantity
    from public.after_sales_hotstamp_film_sync_batches
    where source_file_id = trim(p_source_file_id)
      and source_hash = trim(p_source_hash)
      and status = 'completed';
    if v_batch_id is not null then
        return query select
            v_batch_id, v_saved_rows, v_saved_quantity, true;
        return;
    end if;

    insert into public.after_sales_hotstamp_film_sync_batches (
        source_file_id, source_file_name, source_url,
        source_modified_at, source_hash, start_date, end_date,
        invalid_row_count, operator, status
    ) values (
        trim(p_source_file_id), trim(p_source_file_name),
        coalesce(p_source_url, ''), p_source_modified_at,
        trim(p_source_hash), p_start_date, p_end_date,
        greatest(coalesce(p_invalid_row_count, 0), 0),
        coalesce(nullif(trim(p_operator), ''), 'system'), 'pending'
    ) returning id into v_batch_id;

    insert into public.after_sales_hotstamp_film_entries (
        batch_id, source_file_id, source_file_name,
        source_sheet_name, source_row_number, business_date,
        source_platform, platform, cutting_person, matching_person,
        film_quantity, is_hoodie, multi_press_count, is_white_board,
        hotstamp_person, qa_person
    )
    select
        v_batch_id, trim(p_source_file_id), trim(p_source_file_name),
        trim(row.source_sheet_name), row.source_row_number,
        row.business_date, trim(row.source_platform),
        public.normalize_hotstamp_audit_platform(row.platform),
        trim(coalesce(row.cutting_person, '')),
        trim(coalesce(row.matching_person, '')),
        greatest(row.film_quantity, 0), coalesce(row.is_hoodie, false),
        row.multi_press_count, coalesce(row.is_white_board, false),
        trim(coalesce(row.hotstamp_person, '')),
        trim(coalesce(row.qa_person, ''))
    from jsonb_to_recordset(p_rows) as row(
        source_sheet_name text,
        source_row_number integer,
        business_date date,
        source_platform text,
        platform text,
        cutting_person text,
        matching_person text,
        film_quantity integer,
        is_hoodie boolean,
        multi_press_count integer,
        is_white_board boolean,
        hotstamp_person text,
        qa_person text
    )
    where row.business_date between p_start_date and p_end_date
      and row.source_row_number >= 2
      and trim(coalesce(row.source_platform, '')) <> '';

    get diagnostics v_saved_rows = row_count;
    select coalesce(sum(film_quantity), 0)
    into v_saved_quantity
    from public.after_sales_hotstamp_film_entries saved_entry
    where saved_entry.batch_id = v_batch_id;

    update public.after_sales_hotstamp_film_sync_batches
    set row_count = v_saved_rows,
        total_film_quantity = v_saved_quantity,
        status = 'completed'
    where id = v_batch_id;

    return query select
        v_batch_id, v_saved_rows, v_saved_quantity, false;
end;
$$;

drop function if exists public.get_after_sales_hotstamp_film_comparison(
    date, date
);

create function public.get_after_sales_hotstamp_film_comparison(
    p_start_date date,
    p_end_date date
)
returns table (
    business_date date,
    hotstamp_person text,
    platform text,
    film_quantity bigint,
    source_entry_count bigint,
    hoodie_film_quantity bigint,
    hoodie_entry_count bigint,
    multi_press_quantity bigint,
    multi_press_entry_count bigint,
    system_scan_count bigint,
    system_piece_count bigint
)
language sql stable security definer set search_path = public
as $$
    with source_rows as (
        select
            entry.business_date,
            coalesce(nullif(trim(entry.hotstamp_person), ''),
                '未填写烫印人员') as hotstamp_person,
            public.normalize_hotstamp_audit_platform(entry.platform) as platform,
            sum(entry.film_quantity)::bigint as film_quantity,
            count(*)::bigint as source_entry_count,
            sum(
                case when entry.is_hoodie then entry.film_quantity else 0 end
            )::bigint as hoodie_film_quantity,
            count(*) filter (where entry.is_hoodie)::bigint
                as hoodie_entry_count,
            sum(greatest(coalesce(entry.multi_press_count, 0), 0))::bigint
                as multi_press_quantity,
            count(*) filter (
                where greatest(coalesce(entry.multi_press_count, 0), 0) > 0
            )::bigint as multi_press_entry_count
        from public.after_sales_hotstamp_film_active_entries entry
        where entry.business_date between p_start_date and p_end_date
        group by 1, 2, 3
    ), system_rows as (
        select
            (scan.scanned_at at time zone 'America/New_York')::date
                as business_date,
            trim(scan.hotstamp_by) as hotstamp_person,
            public.normalize_hotstamp_audit_platform(scan.platform) as platform,
            count(*)::bigint as system_scan_count,
            sum(greatest(coalesce(scan.multiple_count, 1), 1))::bigint
                as system_piece_count
        from public.barcode_scans scan
        where scan.hotstamp_by is not null
          and trim(scan.hotstamp_by) <> ''
          and scan.scanned_at >= (
              p_start_date::timestamp at time zone 'America/New_York'
          )
          and scan.scanned_at < (
              (p_end_date + interval '1 day')::timestamp
                  at time zone 'America/New_York'
          )
        group by 1, 2, 3
    )
    select
        coalesce(source.business_date, system.business_date),
        coalesce(source.hotstamp_person, system.hotstamp_person),
        coalesce(source.platform, system.platform),
        coalesce(source.film_quantity, 0),
        coalesce(source.source_entry_count, 0),
        coalesce(source.hoodie_film_quantity, 0),
        coalesce(source.hoodie_entry_count, 0),
        coalesce(source.multi_press_quantity, 0),
        coalesce(source.multi_press_entry_count, 0),
        coalesce(system.system_scan_count, 0),
        coalesce(system.system_piece_count, 0)
    from source_rows source
    full outer join system_rows system
      on system.business_date = source.business_date
     and system.hotstamp_person = source.hotstamp_person
     and system.platform = source.platform
    where p_start_date is not null
      and p_end_date is not null
      and p_end_date >= p_start_date
      and p_end_date - p_start_date <= 366
    order by 1 desc, 2, 3;
$$;

grant select on public.after_sales_hotstamp_film_sync_batches,
    public.after_sales_hotstamp_film_entries,
    public.after_sales_hotstamp_film_active_entries
    to anon, authenticated, service_role;
grant execute on function public.import_after_sales_hotstamp_film_batch(
    text, text, text, timestamptz, text, date, date, jsonb, integer, text
) to anon, authenticated, service_role;
grant execute on function public.get_after_sales_hotstamp_film_comparison(
    date, date
) to anon, authenticated, service_role;

commit;

notify pgrst, 'reload schema';
